### ISSUE TITLE
Need more level music

### ISSUE THREAD

**Issue by 9000-volts** [geckogames/splat#11]
We need more music for levels.

**Comment by GD-Plasman** [comment]
Specifically, which ones?(Name the levels that don’t currently have music)

**Comment by 9000-volts** [comment]
There aren't any levels right now, we just need more music ready for future levels.

**Comment by 1dharmadav** [comment]
Yes, which ones?

FISHY POTATO

On Feb 4, 2015, at 9:28 AM, GD-Plasman notifications@github.com wrote:

Specifically, which ones?(Name the levels that don’t currently have music) 

Sent from Windows Mail 

From: htmlguy 
Sent: ‎Wednesday‎, ‎February‎ ‎4‎, ‎2015 ‎9‎:‎18‎ ‎AM 
To: geckogames/splat 

We need more music for levels.

**Comment by GD-Plasman** [comment]
Well, I'm planning to make the music for Area 51 tomorrow. (or at least starting)

Sent from my Windows Phone
