### ISSUE TITLE
Fix Spike Hitbox

### ISSUE THREAD

**Issue by GD-Plasman** [geckogames/splat#38]
You take damage when a foot away from it!

**Comment by 9000-volts** [comment]
There is nothing wrong with it.
This is because the image of the player is _square_, and the hitbox is _square_. The arm of the player is over the spikes, and therefore it's _square_ hitbox overlaps it's.

**Comment by 9000-volts** [comment]
Removed #bug because it's not a bug.
It's more of an issue that we understand and would have to do too much work to fix, and doesn't cause any trouble ingame.

**Comment by GD-Plasman** [comment]
Just make the spike sprite have more spikes. PROBLEM SOLVED.

**Comment by 9000-volts** [comment]
Not exactly. 
That would make it wider. But the hitbox would still be small. And all the additional width would go to the left.
Also please reply through waffle instead of through email, because your reply text is in the comment.

**Comment by GD-Plasman** [comment]
The fact that it’s wider is all that matters.

**Comment by 9000-volts** [comment]
It will only be wider in one direction so the issue would still exist if the player is on the left-hand side of it.
Also please stop including your email reply text in your comments. (It includes your full name)
